name: "TackleBox Pro"
description: "Verwalte dein Angel-Equipment direkt in Home Assistant"
version: "1.0.1"
slug: "tacklebox_pro"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
panel_icon: "mdi:hook"
panel_title: "TackleBox"
ingress: true
ingress_port: 80
options: {}
schema: {}
